### PR TITLE
Fix SQLiteDatabase.execSQL() without args

### LINKED ISSUE #509: executeSQL(): crashes when executing no-args query
Here is the setup:

	db.executeSQL()
	        .withQuery(RawQuery.builder()
	                .query("DROP TABLE IF EXISTS items")
	                .build())
	        .prepare()
	        .executeAsBlocking();

This fails with following exception:

     Caused by: java.lang.IllegalArgumentException: Empty bindArgs
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1651)
            at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$InternalImpl.executeSQL(DefaultStorIOSQLite.java:286)
            at com.pushtorefresh.storio.sqlite.operations.execute.PreparedExecuteSQL.executeAsBlocking(PreparedExecuteSQL.java:53)

This happens, because overloaded `android.database.sqlite.SQLiteDatabase#execSQL(java.lang.String, java.lang.Object[])` does not accept null `bindArgs` (as per android-23 source), while `DefaultStorIOSQLite` implementation passes `nullableArrayOfStrings(rawQuery.args())` as bindArgs. 

I also tried a workaround:

	db.executeSQL()
	        .withQuery(RawQuery.builder()
	                .query("DROP TABLE IF EXISTS ?")
	                .args("items")
	                .build())
	        .prepare()
	        .executeAsBlocking();

This fails with the following exception:

     Caused by: android.database.sqlite.SQLiteException: near "?": syntax error (code 1): , while compiling: DROP TABLE IF EXISTS ?
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1672)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1653)
            at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$InternalImpl.executeSQL(DefaultStorIOSQLite.java:286)
            at com.pushtorefresh.storio.sqlite.operations.execute.PreparedExecuteSQL.executeAsBlocking(PreparedExecuteSQL.java:53)

I guess, binding is supported for values only (not for table or column names). So, I also doubt code in [this README section](https://github.com/pushtorefresh/storio/blob/master/docs/StorIOSQLite.md#4-execsql-operation) works. Guys, please, take a look.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Fixes #509.

@nikitin-da PTAL!

@vokilam FYI

### CODE REVIEW

File: storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/ui/fragment/TweetsFragment.java [hunk 1]
```diff
@@ -147,7 +147,7 @@ void addTweets() {
         tweets.add(Tweet.newTweet("Google", "Android be together not the same: AOSP, AOSP + Google Apps, Samsung Android"));
         tweets.add(Tweet.newTweet("Reddit", "Now we can send funny gifs directly into your brain via Oculus Rift app!"));
         tweets.add(Tweet.newTweet("ElonMusk", "Tesla Model S OTA update with Android Auto 5.2, fixes for memory leaks"));
-        tweets.add(Tweet.newTweet("AndroidWeekly", "Special issue #1: StorIO — forget about SQLiteDatabase, ContentResolver APIs, ORMs sucks!"));
+        tweets.add(Tweet.newTweet("AndroidWeekly", "Special issue #1: StorIO — forget about SQLiteDatabase, ContentResolver APIs, ORMs suck!"));
```
Comment (nikitin-da) [inline storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/ui/fragment/TweetsFragment.java]: Oh

**Comment by nikitin-da** [comment]
:+1:
