### PR TITLE
Remove toast exceptions swallowing

### LINKED ISSUE #680: question. Why safe toasts?
Why sample app has this safe Toasts.java class. Are toast unsafe or something?
Is it common practice in big projects to have one? 
thx in advance =)

### PR DESCRIPTION
**Pull request by nikitin-da**
Closes #680

### CODE REVIEW

**Comment by rsinukov** [comment]
ok

File: storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/ui/fragment/TweetsFragment.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ void addTweets() {
                 .objects(tweets)
                 .prepare()
                 .asRxObservable()
-                .observeOn(mainThread()) // Remember, all Observables in StorIO already subscribed on Schedulers.io(), you just need to set observeOn()
+                .observeOn(mainThread()) // The default scheduler is Schedulers.io(), all Observables in StorIO already subscribed on this scheduler, you just need to set observeOn()
```
Comment (artem-zinnatullin) [inline storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/ui/fragment/TweetsFragment.java]: 👍
