### PR TITLE
Fix incorrect test parallelWritesWithoutTransaction.

### LINKED ISSUE #826: CI freezes.
We're seeing "random" CI freezes for a long time, sometimes more often.

Latest observed logs from 2 different builds show that latest test in the output before freeze is:

```console
com.pushtorefresh.storio2.sqlite.integration.RxQueryTest > queryOneExistedObjectTableUpdate PASSED
```

So my guess is that one of the tests in `RxQueryTest` has racy deadlock. 

I'd start solving it by adding [Timeout rule](https://github.com/junit-team/junit4/wiki/Timeout-for-tests) for whole `RxQueryTest` with reasonable timeout ie 30 seconds, that way we'll figure out which test causes the problem because it'll fail the build properly.

@nikitin-da can you please try that if you have time? Otherwise I'll take care of that later :)

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Fixes #826.

TL;TR: test was incorrect, because default PutResolver uses short-term transaction thus StorIO has all rights to merge notifications, so sometimes we've seen flakiness due to notifications merge.

CI was freezing because we were awaiting for wrong amount of notifications without timeout, this PR adds timeout to all tests and `RepeatRule` to make sure our concurrent tests are good.

Thanks a lot @nikitin-da for his work in #827, those logs really helped to figure out what was wrong!

### CODE REVIEW

File: storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java [hunk 1]
```diff
@@ -197,11 +203,12 @@ public void run() {
     }
 
     @Test
+    @Repeat(times = 20)
     public void shouldReceiveOneNotificationWithAllAffectedTablesInTransactionWithMultipleThreads() throws InterruptedException {
         final String table1 = "test_table1";
         final String table2 = "test_table2";
 
-        final int numberOfThreads = 100;
+        final int numberOfThreads = 50;
```
Comment (artem-zinnatullin) [inline storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java]: 100 might be a problem for Travis since it has limited amount of resources

File: storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java [hunk 2]
```diff
@@ -239,14 +246,15 @@ public void run() {
         // Steady!
         startAllThreadsLock.countDown(); // Go!
 
-        assertThat(allThreadsFinishedLock.await(20, SECONDS)).isTrue();
+        assertThat(allThreadsFinishedLock.await(25, SECONDS)).isTrue();
```
Comment (artem-zinnatullin) [inline storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java]: Doesn't really matter, but since 30 seconds is now global limit for test duration, increasing this closer to 30 kinda makes sense :)

File: storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java [hunk 3]
```diff
@@ -197,11 +203,12 @@ public void run() {
     }
 
     @Test
+    @Repeat(times = 20)
```
Comment (artem-zinnatullin) [inline storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/NotifyAboutChangesTest.java]: I've seen this test failed on #827 PR build, but I don't think I ever saw it fail before, so I just added `@Repeat` to make sure it's good, I've read it carefully and still think it's a good test as is :)

File: storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/RxQueryTest.java [hunk 4]
```diff
@@ -151,19 +157,20 @@ public void deleteEmission() {
     }
 
     @Test
-    public void parallelWritesWithoutTransaction() {
-        final int numberOfParallelWorkers = 50;
+    @Repeat(times = 20)
+    public void parallelPutWithoutGlobalTransaction() {
+        final int numberOfParallelPuts = 50;
```
Comment (artem-zinnatullin) [inline storio-sqlite/src/test/java/com/pushtorefresh/storio2/sqlite/integration/RxQueryTest.java]: Just rename :)

**Comment by artem-zinnatullin** [comment]
Ah, didn't update `take()` properly

**Comment by artem-zinnatullin** [comment]
@nikitin-da I'm merging this to unblock other PRs, please feel free to comment, I'll open separate PR to fix your comments if needed!

@geralt-encore thanks for review!

File: storio-test-common/src/main/java/com/pushtorefresh/storio2/test/RepeatRule.java [hunk 5]
```diff
@@ -0,0 +1,36 @@
+package com.pushtorefresh.storio2.test;
+
+import android.support.annotation.NonNull;
+
+import org.junit.rules.TestRule;
+import org.junit.runner.Description;
+import org.junit.runners.model.Statement;
+
+public class RepeatRule implements TestRule {
```
Comment (nikitin-da) [inline storio-test-common/src/main/java/com/pushtorefresh/storio2/test/RepeatRule.java]: Nice!

**Comment by nikitin-da** [comment]
@artem-zinnatullin great work man!
