### PR TITLE
Treat all Java Compiler and Android Lint warnings as errors

### LINKED ISSUE #200: Treat javac and lint warnings as errors
Currently, Jenkins checks for `javac` warnings and if warning will be found -> build will fail.

But I noticed, that Jenkins `Warning` plugin works very slow, it takes about 2 minutes to analyse all the build output.

I am going to configure `javac` and `lint` to treat all warnings as errors so we will be sure that everything is okay and it should be faster than post-processing of build output on the Jenkins.

Also, it will make `ci/ci.sh` really cross-environment-platform solution, because behavior of the build will be same on developers machines and on the CI.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #200

I had to fix several Java Compiler warnings and Android Lint warnings to make successful build, so it works :D

@nikitin-da PTAL

### CODE REVIEW

File: storio-sqlitedb/src/test/java/com/pushtorefresh/storio/sqlitedb/operation/put/PutStub.java [hunk 1]
```diff
@@ -68,13 +69,11 @@ private PutStub(boolean useTransaction, int numberOfItems) {
         when(storIOSQLiteDb.put())
                 .thenReturn(new PreparedPut.Builder(storIOSQLiteDb));
 
-        //noinspection unchecked
```
Comment (nikitin-da) [inline storio-sqlitedb/src/test/java/com/pushtorefresh/storio/sqlitedb/operation/put/PutStub.java]: Suppressing for statement didn't work, did it?

**Comment by nikitin-da** [comment]
retest this please
