### PR TITLE
Corrections for all builders

### LINKED ISSUE #218: Compile checkable required params for all builders
I really don't like that our builders can be used incorrectly and if user would forget required param he will see this only in runtime, and it will be crash or the application..

We can make incorrect usage of builders non-compilable, there is workaround for this via interfaces: http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

@nikitin-da do you agree?

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #218

@nikitin-da review please :)

### CODE REVIEW

File: storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java [hunk 1]
```diff
@@ -103,9 +102,7 @@ public String toString() {
     /**
      * Builder for {@link Query}
      */
-    public static class Builder {
-
-        Uri uri;
+    public static final class Builder {
```
Comment (nikitin-da) [inline storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java]: Why did you decide to make it final? Can it be useful for user to extend it for some custom behavior. For example receive `String` instead of `Uri`?

**Comment by nikitin-da** [comment]
:+1:

File: storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java (hunk 1 above)
Comment (artem-zinnatullin) [inline storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java]: But how he would apply his custom class?

вс, 26 апр. 2015, 14:54, Dmitrii Nikitin <notifications@github.com>:

Comment (nikitin-da) [inline storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java]: `class CustomBuilder exteds Query.Builder {
   CompleteBuilder uri(java.net.URI javaUri) {
      return(javaUri.toString());
   }
}`
and then
storIOContentResolver()
                .get()
                .cursor()
                .withQuery(new Query.CustomBuilder()
                        .uri(existJavaUri)
                        .build())
`
Of cause, it is far-fetched example, but are you sure that it will be not necessary or just want to hide all except really important?

Comment (artem-zinnatullin) [inline storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/query/Query.java]: It won't work, you'll have to use custom Query class for that or modify
sources of Query class and build StorIO from sources. Yep, I want to hide
and make final everything to be sure that won't have to support inheritance
of our classes

вс, 26 апр. 2015, 19:57, Dmitrii Nikitin <notifications@github.com>:
