### PR TITLE
Fix Rx memory leak in StorIOContentResolver

### LINKED ISSUE #359: StorIOContentResolver has memory leak
My fault, forget to add unsubscribing from `ContentObserver` — memory leak.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #359, and little refactoring (of course :).

@nikitin-da PTAL, my fault :(

### CODE REVIEW

**Comment by nikitin-da** [comment]
Oh, no. Delete emission =(

**Comment by nikitin-da** [comment]
retest this please

**Comment by artem-zinnatullin** [comment]
Looks like it's emulator problem, I'll restart it later.
4 июня 2015 г. 8:03 AM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Comment by nikitin-da** [comment]
Hm, no it isn't. Delete emission test was failed first time

**Comment by nikitin-da** [comment]
retest this please

File: storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    }
+
+    @Test
+    public void shouldRegisterContentObserverForPassedUris() {
+        Set<Uri> uris = new HashSet<Uri>();
+
+        // All Uris are different (objects)
+        uris.add(mock(Uri.class));
+        uris.add(mock(Uri.class));
+        uris.add(mock(Uri.class));
```
Comment (nikitin-da) [inline storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java]: Hm, wasn't very obivious for me

**Comment by nikitin-da** [comment]
Ok)

**Comment by nikitin-da** [comment]
Cool! Did LeakCanary help you?

**Comment by artem-zinnatullin** [comment]
Nope, just reviewed code and saw epic fail.
4 июня 2015 г. 8:43 AM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

File: storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java (hunk 1 above)
Comment (artem-zinnatullin) [inline storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java]: You are talking about `mock(Uri.class)`? If so, yep, each object will be unique.

Comment (nikitin-da) [inline storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java]: Yep, I understand, but it wasn't so clearly that you will rely on mocked object equality. Also, imho it will be a bit harder to debug.

Comment (artem-zinnatullin) [inline storio-content-resolver/src/test/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserverTest.java]: Equals of mocked objects just compares references, which is okay for such
tests :)
4 июня 2015 г. 3:03 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:
