### PR TITLE
Fix flaky integration tests for StorIOSQLite, ignore some tests for StorIOContentResolver

### LINKED ISSUE #355: Rewrite flaky integration tests
See #354.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #355.

@nikitin-da PTAL

### CODE REVIEW

File: storio-content-resolver/src/androidTest/java/com/pushtorefresh/storio/content_resolver/impl/ObserveChangesTest.java [hunk 1]
```diff
@@ -16,15 +21,17 @@
 import rx.functions.Action1;
 import rx.schedulers.Schedulers;
 
-public class ObserveChangesTest extends BaseSubscriptionTest {
+@RunWith(AndroidJUnit4.class)
```
Comment (artem-zinnatullin) [inline storio-content-resolver/src/androidTest/java/com/pushtorefresh/storio/content_resolver/impl/ObserveChangesTest.java]: @nikitin-da without this annotation your tests in this class didn't run, and I had to ignore them for now, because `ProviderTestCase2` does not call contentObserver :(

**Comment by artem-zinnatullin** [comment]
Yes! Passed, I'll check few more times.

**Comment by artem-zinnatullin** [comment]
retest this please

**Comment by nikitin-da** [comment]
retest this please

File: storio-test-common/src/test/java/com/pushtorefresh/storio/test/AbstractEmissionCheckerTest.java [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+    public void shouldAssertThatNextExpectedValueReceived() {
+        Queue<String> expectedValues = new LinkedList<String>();
+        expectedValues.add("test_value");
+
+        AbstractEmissionChecker<String> emissionChecker = new AbstractEmissionChecker<String>(expectedValues) {
+            @NonNull
+            @Override
+            public Subscription subscribe() {
+                return Observable
+                        .just("test_value")
```
Comment (nikitin-da) [inline storio-test-common/src/test/java/com/pushtorefresh/storio/test/AbstractEmissionCheckerTest.java]: Maybe will be better to move it to variable?

Comment (nikitin-da) [inline storio-test-common/src/test/java/com/pushtorefresh/storio/test/AbstractEmissionCheckerTest.java]: Or maybe not

Comment (artem-zinnatullin) [inline storio-test-common/src/test/java/com/pushtorefresh/storio/test/AbstractEmissionCheckerTest.java]: More lines :)
2 июня 2015 г. 11:24 AM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Comment by nikitin-da** [comment]
All rewrote) Thank you very much.

**Comment by artem-zinnatullin** [comment]
:+1:
